/**
 * The page-world interceptor.
 *
 * This is the only code in the extension that runs in the page's own world,
 * and it is deliberately the smallest and dullest file here, because it is
 * also the one a store reviewer will read most carefully.
 *
 * What it does: wraps fetch and XMLHttpRequest, and for the handful of
 * addresses an adapter claims, tees the response so the body can be read
 * without consuming it. It then posts the request and response text to the
 * isolated content script through a nonce-guarded event.
 *
 * What it does not do, and what the shape of the file is meant to make
 * obvious: it never reads cookies, never touches localStorage, never inspects
 * a request it was not asked about, never modifies a request or a response,
 * and never opens a connection of its own. The page's traffic goes where the
 * page sent it, unchanged.
 *
 * The nonce is generated by the isolated script and handed in, so a page
 * cannot forge a turn by dispatching the same event.
 */

export interface InterceptorConfig {
  nonce: string;
  /** Addresses worth reading, as source strings for regular expressions. */
  patterns: string[];
  /** Bodies larger than this are skipped rather than held in memory. */
  maxBodyBytes: number;
}

export interface InterceptedExchange {
  url: string;
  method: string;
  requestBody: string;
  responseBody: string;
  requestHeaders: Record<string, string>;
  at: string;
}

export const EVENT_NAME = 'buoa:exchange';

/** Written as a standalone function so it can be injected as a string. */
export const installInterceptor = (config: InterceptorConfig): (() => void) => {
  const patterns = config.patterns.map((source) => new RegExp(source));
  const wanted = (url: string, method: string): boolean =>
    method.toUpperCase() === 'POST' && patterns.some((pattern) => pattern.test(url));

  const publish = (exchange: InterceptedExchange): void => {
    window.dispatchEvent(
      new CustomEvent(EVENT_NAME, { detail: { nonce: config.nonce, exchange } }),
    );
  };

  const headerRecord = (init?: HeadersInit): Record<string, string> => {
    const out: Record<string, string> = {};
    if (!init) return out;
    // Only the headers an adapter needs to name a model. Nothing that
    // authenticates anything is copied.
    const keep = new Set(['x-goog-ext-525001261-jspb', 'content-type']);
    const add = (key: string, value: string): void => {
      const lower = key.toLowerCase();
      if (keep.has(lower)) out[lower] = value;
    };
    if (init instanceof Headers) init.forEach((value, key) => add(key, value));
    else if (Array.isArray(init)) for (const [key, value] of init) add(key, value);
    else for (const [key, value] of Object.entries(init)) add(key, String(value));
    return out;
  };

  const originalFetch = window.fetch;

  const wrappedFetch: typeof window.fetch = async (input, init) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    const method = init?.method ?? (input instanceof Request ? input.method : 'GET');

    if (!wanted(url, method)) return originalFetch.call(window, input as RequestInfo, init);

    let requestBody = '';
    try {
      if (typeof init?.body === 'string') requestBody = init.body;
      else if (input instanceof Request) requestBody = await input.clone().text();
    } catch {
      // A body we cannot read is a turn we cannot count. Carry on regardless:
      // the page's request must not be affected by our failure to read it.
    }

    const response = await originalFetch.call(window, input as RequestInfo, init);

    /*
     * Tee the stream. One branch goes to the page untouched, the other is read
     * by us. Reading the page's branch instead would consume it and break the
     * site, which is the failure mode this whole approach has to avoid.
     */
    try {
      if (response.body) {
        const [forPage, forUs] = response.body.tee();
        const mirrored = new Response(forPage, {
          status: response.status,
          statusText: response.statusText,
          headers: response.headers,
        });

        void (async () => {
          const reader = forUs.getReader();
          const decoder = new TextDecoder();
          let text = '';
          let bytes = 0;
          for (;;) {
            const { done, value } = await reader.read();
            if (done) break;
            bytes += value.byteLength;
            if (bytes > config.maxBodyBytes) {
              // Too large to hold. Drain the rest so the branch closes cleanly.
              continue;
            }
            text += decoder.decode(value, { stream: true });
          }
          text += decoder.decode();
          publish({
            url,
            method,
            requestBody,
            responseBody: bytes > config.maxBodyBytes ? '' : text,
            requestHeaders: headerRecord(init?.headers ?? (input instanceof Request ? input.headers : undefined)),
            at: new Date().toISOString(),
          });
        })();

        return mirrored;
      }
    } catch {
      // Anything at all goes wrong here and the page still gets its response.
    }

    return response;
  };

  window.fetch = wrappedFetch;

  const OriginalXHR = window.XMLHttpRequest;
  class WrappedXHR extends OriginalXHR {
    private buoaUrl = '';
    private buoaMethod = '';
    private buoaBody = '';

    override open(
      method: string,
      url: string | URL,
      async = true,
      username?: string | null,
      password?: string | null,
    ): void {
      this.buoaMethod = method;
      this.buoaUrl = typeof url === 'string' ? url : url.href;
      super.open(method, url, async, username, password);
    }

    override send(body?: Document | XMLHttpRequestBodyInit | null): void {
      if (typeof body === 'string') this.buoaBody = body;
      if (wanted(this.buoaUrl, this.buoaMethod)) {
        this.addEventListener('load', () => {
          try {
            publish({
              url: this.buoaUrl,
              method: this.buoaMethod,
              requestBody: this.buoaBody,
              responseBody: typeof this.responseText === 'string' ? this.responseText : '',
              requestHeaders: {},
              at: new Date().toISOString(),
            });
          } catch {
            // Never let our listener throw into the page's handler.
          }
        });
      }
      super.send(body);
    }
  }
  window.XMLHttpRequest = WrappedXHR as unknown as typeof XMLHttpRequest;

  /** Puts everything back, for a clean unload and for the tests. */
  return () => {
    window.fetch = originalFetch;
    window.XMLHttpRequest = OriginalXHR;
  };
};
